# TRMNLP configuration
# {{ env.VARIABLE }} interpolation is available here
---
# auto-reload when files change (`watch: false` to disable)
watch:
  - .trmnlp.yml
  - src

# values of custom fields (defined in src/settings.yml)
custom_fields:
  {
    base_url: "https://de.sentry.io",
    api_key: "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",
    organization: "theodo-v0",
    projects: "4510108489678928",
    period: "24h",
  }

# override variables
variables:
  trmnl: {}
